name: Update README

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update README.md
        run: |
          echo "### 📊 GitHub Stats:" > README.md
          echo '<p align="center">' >> README.md
          echo '<img src="https://github-readme-stats.vercel.app/api?username=lleenx&show_icons=true&theme=tokyonight&count_private=true&include_all_commits=true" />' >> README.md
          echo '</p>' >> README.md

          echo "### 🔥 Most Used Languages:" >> README.md
          echo '<p align="center">' >> README.md
          echo '<img src="https://github-readme-stats.vercel.app/api/top-langs/?username=lleenx&layout=compact&theme=tokyonight" />' >> README.md
          echo '</p>' >> README.md

      - name: Commit & Push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m 'Update README with stats' || echo "No changes"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/lleenx/lleenx.git HEAD:main
