name: Update GitHub Stats in Profile

on:
  schedule:
    - cron: '0 * * * *'  # update tiap jam
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Generate Stats
        run: |
          curl -o stats.svg "https://github-readme-stats.vercel.app/api?username=lleenx&show_icons=true&theme=tokyonight&count_private=true&include_all_commits=true&hide=contribs"
          curl -o langs.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=lleenx&layout=compact&theme=tokyonight&count_private=true"

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update stats [auto]" || echo "No changes to commit"
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
